### ISSUE TITLE
Replacement doesn't happen

### ISSUE THREAD

**Issue by pepa65** [echocat/caddy-filter#2]
Caddy 0.9.4 here.
I have:
```
  filter rule {
    path .*\.md
    search_pattern "<a href=\"http"
    replacement "<a class=\"http\" href=\"http"
  }

```
I tried using single quotes around the patterns, but that just gave "Parse error: Wrong argument count or unexpected line ending". I hope there is a way to escape double-quotes in patterns.

**Comment by blaubaer** [comment]
Hi @pepa65!

I cannot reproduce this problem on CentOS 7.3 and Windows 10 and the latest downloaded version of Caddy (0.9.4 from https://caddyserver.com/download which bundles the filter plugin).
It works fine for me with the following config:
```txt
localhost:2020
root .
filter rule {
    path .*\.md
    search_pattern "<a href=\"http"
    replacement "<a class=\"http\" href=\"http"
}
```
It starts and renders the content as expected.

But - There is something important to know: If you have a mapping that maps ``/foo.md`` in your sources to ``/foo.html`` than you have to provide in ``path`` property ``path .*\.html`` instead of ``path .*\.md`` because this filter applies to the request URI not to the file system paths.

**Comment by pepa65** [comment]
I wonder if it's an interaction with markdown.
If I use the same Caddyfile as you posted, but start with markdown, it doesn't work. I would expect that the filter would work on the results of the markdown. (The output of markdown is very basic, so I want to add some classes here and there. I'm now doing it in javascript, but it sounded like filter was meant for this.)

**Comment by blaubaer** [comment]
Could you provide a ZIP with a minimal setup that is not working for you incl. the full request to do (like: http://localhost:8080/foo.html)? So I have all file to reproduce the problem your describe.

Thank you.

**Comment by pepa65** [comment]
[problem.zip](https://github.com/echocat/caddy-filter/files/675614/problem.zip)

Caddyfile:
```
localhost:2020
root .
markdown
filter rule {
    path .*\.md
    search_pattern "<a href=\"http"
    replacement "<a class=\"http\" href=\"http"
}
```

index.md:
```
# Test page

[wikilink](/two.md)

[external link](http://github.com)

```

**Comment by blaubaer** [comment]
Oh! Now I can reproduce the problem. This happens only if the ``markdown`` configuration was enabled. In this case the ``filter`` plugin is not call for interception by caddy. I will start a depper investigation for this. Thank for file and explain the problem.

**Comment by francislavoie** [comment]
Doesn't seem to work on `proxy` responses either.

**Comment by blaubaer** [comment]
Found the reason: The position in [``directives@plugin.go``](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go#L392) was badly chose. I've created a [pull request](https://github.com/mholt/caddy/pull/1323) which should fix this.

**Comment by blaubaer** [comment]
Ok. This fix is merged in caddy. Once this fix (in caddy itself) is released this bug of caddy-filter is also fixed. I let this issue open until a new release of caddy.

**Comment by francislavoie** [comment]
Just a heads up regarding a different issue I just saw for Caddy, https://github.com/mholt/caddy/issues/1310#issuecomment-269659362 filter might fail to work on proxied requests like those described there. Looks like they don't buffer the entire request in those cases so the only way filter would work in that case would be if it was streamed... which I think is probably out of scope of this plugin.

I haven't tested this at all, just something that came to mind when I read that issue.

**Comment by francislavoie** [comment]
Got around to trying the fix, still doesn't work on `proxy` responses. Has that been tested by anyone else? I tried doing this:

        filter rule {
                path .*
                search_pattern </body>
                replacement "SOMESTUFF</body>"
        }

I see no changed in the returned HTML. I have a feeling the reverse proxy module skips the post-response events. I don't know.

**Comment by francislavoie** [comment]
I just got around to trying it with `proxy` (rebuilt from source), and it seems to work now, BUT it didn't seem to work at first because the proxied page implements caching and it looks like `filter` doesn't get applied if the response is cached. My assumption was that it would always run regardless of caching. Is that intended? If not, wouldn't mind an option or something to force always filtering.

Edit: Oh, nop, the caching is client-side. Disregard. Should be fine.

**Comment by mwpastore** [comment]
Something is still not quite when `filter` is used in a vhost with `proxy`. I can't quite put my finger on it but it's almost as if Content-Length isn't being updated after the filter is applied. For example: the original source content (returned by the proxy) is 26 bytes, the content after the filter is applied should be 38 bytes, and here's the output of curl:

```
HTTP/1.1 200 OK
Content-Length: 26
Content-Type: text/html; charset=UTF-8
Date: Fri, 06 Jan 2017 05:48:35 GMT
Server: Caddy

curl: (18) transfer closed with 26 bytes remaining to read
```

If I add this to the proxy stanza:

```
header_downstream Content-Length 38
```

The `curl` succeeds and returns the correct output.

**Comment by blaubaer** [comment]
@mwpastore what do you describe is part of #3.

**Comment by mwpastore** [comment]
@blaubaer I'm running with that patch and experiencing this behavior.

**Comment by blaubaer** [comment]
@mwpastore - understand. But please add this report to #3 - I already reopened this issue and will try to fix it. Could you please also attach example configuration to it that I'am able to reproduce it easier? Thank you!

**Comment by mwpastore** [comment]
@blaubaer Gotcha. Will do.

**Comment by blaubaer** [comment]
Tested with current caddy version 0.9.5 and works now as expected.

**Comment by pepa65** [comment]
Doesn't work for me, caddy 0.9.5, config as in [earlier comment](https://github.com/echocat/caddy-filter/issues/2#issuecomment-269476466)

**Comment by blaubaer** [comment]
I will recheck this. Thank for your input.

**Comment by blaubaer** [comment]
Dear @pepa65,

your config works but only if you call http://localhost/index.md if you want to be able also to call http://localhost/ your path parameter have to look like this:

```
path ^/|.*\.md$
```

**Important hint:** Based on the still existing bug #3 please also activate ```gzip``` to workaround this problem.

**Comment by pepa65** [comment]
Thanks for the help, and for the fix!
